In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/khushikyad001/public-transport-delays-with-weather-and-events/public_transport_delays.csv

In [2]:
df = pd.read_csv(
    '/kaggle/input/datasets/khushikyad001/public-transport-delays-with-weather-and-events/public_transport_delays.csv'
)

In [3]:
df.head()

,trip_id,date,time,transport_type,route_id,origin_station,destination_station,scheduled_departure,scheduled_arrival,actual_departure_delay_min,...,wind_speed_kmh,precipitation_mm,event_type,event_attendance_est,traffic_congestion_index,holiday,peak_hour,weekday,season,delayed
0,T00000,2023-01-01,05:00:00,Tram,Route_15,Station_31,Station_6,05:02:00,05:55:00,12,...,46,13.0,NaN,500,81,0,1,6,Winter,0
1,T00001,2023-01-01,05:15:00,Metro,Route_12,Station_49,Station_32,05:16:00,05:55:00,15,...,11,11.4,NaN,0,53,0,0,6,Autumn,1
2,T00002,2023-01-01,05:30:00,Bus,Route_16,Station_29,Station_42,05:33:00,06:17:00,0,...,31,14.1,Sports,0,67,1,0,6,Autumn,0
3,T00003,2023-01-01,05:45:00,Tram,Route_19,Station_26,Station_18,05:49:00,06:08:00,15,...,41,6.4,NaN,500,84,0,0,6,Winter,1
4,T00004,2023-01-01,06:00:00,Tram,Route_8,Station_18,Station_15,06:00:00,06:35:00,-1,...,30,18.5,NaN,500,46,0,0,6,Spring,1

In [4]:
df.shape

(2000, 24)

In [5]:
df.columns.tolist()

['trip_id',
 'date',
 'time',
 'transport_type',
 'route_id',
 'origin_station',
 'destination_station',
 'scheduled_departure',
 'scheduled_arrival',
 'actual_departure_delay_min',
 'actual_arrival_delay_min',
 'weather_condition',
 'temperature_C',
 'humidity_percent',
 'wind_speed_kmh',
 'precipitation_mm',
 'event_type',
 'event_attendance_est',
 'traffic_congestion_index',
 'holiday',
 'peak_hour',
 'weekday',
 'season',
 'delayed']

In [6]:
df.columns.tolist()

['trip_id',
 'date',
 'time',
 'transport_type',
 'route_id',
 'origin_station',
 'destination_station',
 'scheduled_departure',
 'scheduled_arrival',
 'actual_departure_delay_min',
 'actual_arrival_delay_min',
 'weather_condition',
 'temperature_C',
 'humidity_percent',
 'wind_speed_kmh',
 'precipitation_mm',
 'event_type',
 'event_attendance_est',
 'traffic_congestion_index',
 'holiday',
 'peak_hour',
 'weekday',
 'season',
 'delayed']

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df = pd.read_csv('/kaggle/input/datasets/khushikyad001/public-transport-delays-with-weather-and-events/public_transport_delays.csv')

print(df.shape)

(2000, 24)

In [9]:
df.columns.tolist()

['trip_id',
 'date',
 'time',
 'transport_type',
 'route_id',
 'origin_station',
 'destination_station',
 'scheduled_departure',
 'scheduled_arrival',
 'actual_departure_delay_min',
 'actual_arrival_delay_min',
 'weather_condition',
 'temperature_C',
 'humidity_percent',
 'wind_speed_kmh',
 'precipitation_mm',
 'event_type',
 'event_attendance_est',
 'traffic_congestion_index',
 'holiday',
 'peak_hour',
 'weekday',
 'season',
 'delayed']

In [10]:
df['event_type'] = df['event_type'].fillna('None')

In [11]:
df['event_type'].isnull().sum()

np.int64(0)

In [12]:
y = df['delayed']

In [13]:
y.head()

0    0
1    1
2    0
3    1
4    1
Name: delayed, dtype: int64

In [14]:
X = df.drop(
    columns=[
        'delayed',
        'actual_arrival_delay_min'
    ]
)

In [15]:
X = X.drop(
    columns=[
        'trip_id',
        'origin_station',
        'destination_station'
    ]
)

In [16]:
X.columns

Index(['date', 'time', 'transport_type', 'route_id', 'scheduled_departure',
       'scheduled_arrival', 'actual_departure_delay_min', 'weather_condition',
       'temperature_C', 'humidity_percent', 'wind_speed_kmh',
       'precipitation_mm', 'event_type', 'event_attendance_est',
       'traffic_congestion_index', 'holiday', 'peak_hour', 'weekday',
       'season'],
      dtype='object')

In [17]:
X = pd.get_dummies(
    X,
    drop_first=True
)

In [18]:
X.shape

(2000, 1701)

In [19]:
X.head()

,actual_departure_delay_min,temperature_C,humidity_percent,wind_speed_kmh,precipitation_mm,event_attendance_est,traffic_congestion_index,holiday,peak_hour,weekday,...,weather_condition_Snow,weather_condition_Storm,event_type_Festival,event_type_None,event_type_Parade,event_type_Protest,event_type_Sports,season_Spring,season_Summer,season_Winter
0,12,5.1,52,46,13.0,500,81,0,1,6,...,False,True,False,True,False,False,False,False,False,True
1,15,34.0,64,11,11.4,0,53,0,0,6,...,False,False,False,True,False,False,False,False,False,False
2,0,29.5,35,31,14.1,0,67,1,0,6,...,False,False,False,False,False,False,True,False,False,False
3,15,27.4,55,41,6.4,500,84,0,0,6,...,False,False,False,True,False,False,False,False,False,True
4,-1,0.1,90,30,18.5,500,46,0,0,6,...,True,False,False,True,False,False,False,True,False,False

In [20]:
print(X.shape)

(2000, 1701)

In [21]:
pd.get_dummies(X)

,actual_departure_delay_min,temperature_C,humidity_percent,wind_speed_kmh,precipitation_mm,event_attendance_est,traffic_congestion_index,holiday,peak_hour,weekday,...,weather_condition_Snow,weather_condition_Storm,event_type_Festival,event_type_None,event_type_Parade,event_type_Protest,event_type_Sports,season_Spring,season_Summer,season_Winter
0,12,5.1,52,46,13.0,500,81,0,1,6,...,False,True,False,True,False,False,False,False,False,True
1,15,34.0,64,11,11.4,0,53,0,0,6,...,False,False,False,True,False,False,False,False,False,False
2,0,29.5,35,31,14.1,0,67,1,0,6,...,False,False,False,False,False,False,True,False,False,False
3,15,27.4,55,41,6.4,500,84,0,0,6,...,False,False,False,True,False,False,False,False,False,True
4,-1,0.1,90,30,18.5,500,46,0,0,6,...,True,False,False,True,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,15,17.2,98,35,4.6,0,96,0,0,5,...,False,True,False,True,False,False,False,False,False,True
1996,11,0.0,89,44,15.4,0,12,0,1,6,...,True,False,True,False,False,False,False,False,False,True
1997,1,12.9,95,32,2.7,0,24,1,0,6,...,True,False,False,True,False,False,False,False,True,False
1998,7,17.8,55,35,8.8,2000,23,0,0,6,...,False,False,False,True,False,False,False,False,True,False
1999,0,19.2,98,1,14.0,50000,28,0,0,6,...,False,True,False,True,False,False,False,True,False,False

In [22]:
for col in [
    'route_id',
    'date',
    'time',
    'scheduled_departure',
    'scheduled_arrival'
]:
    print(col, df[col].nunique())

route_id 20
date 22
time 96
scheduled_departure 474
scheduled_arrival 1068

In [31]:
df2 = df.copy()

df2['event_type'] = df2['event_type'].fillna('None')

X = df2.drop(
    columns=[
        'delayed',
        'actual_arrival_delay_min',
        'trip_id',
        'origin_station',
        'destination_station',
        'date',
        'time',
        'scheduled_departure',
        'scheduled_arrival',
        'route_id'
    ]
)

y = df2['delayed']

In [29]:
X = pd.get_dummies(X, drop_first=True)

In [30]:
print(X.shape)

(2000, 26)

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(1600, 14)
(400, 14)

In [34]:
X.dtypes

transport_type                 object
actual_departure_delay_min      int64
weather_condition              object
temperature_C                 float64
humidity_percent                int64
wind_speed_kmh                  int64
precipitation_mm              float64
event_type                     object
event_attendance_est            int64
traffic_congestion_index        int64
holiday                         int64
peak_hour                       int64
weekday                         int64
season                         object
dtype: object

In [35]:
X.select_dtypes(include=['object']).columns

Index(['transport_type', 'weather_condition', 'event_type', 'season'], dtype='object')

In [37]:
X = pd.get_dummies(X, drop_first=True)

In [38]:
print(X.shape)

(2000, 26)

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [49]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [43]:
X.select_dtypes(include=['object']).columns

Index([], dtype='object')

In [52]:
pred = model.predict(X_test)

In [53]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, pred)

print("Accuracy:", accuracy)

Accuracy: 0.745

In [54]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       100
           1       0.75      0.99      0.85       300

    accuracy                           0.74       400
   macro avg       0.37      0.50      0.43       400
weighted avg       0.56      0.74      0.64       400

In [55]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, pred))

[[  0 100]
 [  2 298]]

In [56]:
import pandas as pd

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(
    'Importance',
    ascending=False
)

print(importance.head(10))

                       Feature  Importance
1                temperature_C    0.120317
4             precipitation_mm    0.120089
6     traffic_congestion_index    0.111832
3               wind_speed_kmh    0.109534
2             humidity_percent    0.108042
0   actual_departure_delay_min    0.085089
9                      weekday    0.062372
5         event_attendance_est    0.034168
19             event_type_None    0.018765
8                    peak_hour    0.018211

In [57]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [60]:
model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced'
)

In [62]:
model.fit(X_train, y_train)

pred = model.predict(X_test)

In [63]:
classification_report(y_test, pred)

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

'              precision    recall  f1-score   support\n\n           0       0.00      0.00      0.00       100\n           1       0.75      1.00      0.86       300\n\n    accuracy                           0.75       400\n   macro avg       0.38      0.50      0.43       400\nweighted avg       0.56      0.75      0.64       400\n'

In [64]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import classification_report

dummy = DummyClassifier(
    strategy="most_frequent"
)

dummy.fit(X_train, y_train)

dummy_pred = dummy.predict(X_test)

print(classification_report(
    y_test,
    dummy_pred
))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       100
           1       0.75      1.00      0.86       300

    accuracy                           0.75       400
   macro avg       0.38      0.50      0.43       400
weighted avg       0.56      0.75      0.64       400

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [83]:
class_weight='balanced'

In [84]:
df['delayed'].value_counts()

delayed
1    1499
0     501
Name: count, dtype: int64

In [85]:
df.groupby('delayed')[
    'actual_arrival_delay_min'
].describe()

          count       mean       std  min   25%   50%   75%   max
delayed
0         501.0   1.049900  2.617538 -3.0  -1.0   1.0   3.0   5.0
1        1499.0  17.418279  6.761271  6.0  11.0  17.0  23.0  29.0

In [89]:
y = df['actual_arrival_delay_min']

In [92]:
from sklearn.ensemble import RandomForestRegressor

In [93]:
from sklearn.metrics import mean_absolute_error, r2_score

In [94]:
df.groupby('delayed')['actual_arrival_delay_min'].describe()

          count       mean       std  min   25%   50%   75%   max
delayed
0         501.0   1.049900  2.617538 -3.0  -1.0   1.0   3.0   5.0
1        1499.0  17.418279  6.761271  6.0  11.0  17.0  23.0  29.0

In [100]:
df2 = df.copy()

df2['event_type'] = df2['event_type'].fillna('None')

In [103]:
y = df2['actual_arrival_delay_min']

In [104]:
X = df2.drop(
    columns=[
        'actual_arrival_delay_min',
        'delayed',
        'trip_id',
        'origin_station',
        'destination_station',
        'date',
        'time',
        'scheduled_departure',
        'scheduled_arrival'
    ]
)

In [106]:
X = pd.get_dummies(X, drop_first=True)

In [107]:
print(X.shape)

(2000, 45)

In [109]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [110]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [111]:
pred = model.predict(X_test)

In [112]:
from sklearn.metrics import mean_absolute_error, r2_score

print("MAE:", mean_absolute_error(y_test, pred))
print("R2:", r2_score(y_test, pred))

MAE: 7.8060125
R2: -0.028207156604521444